### ISSUE TITLE
Develop page detail for movie

### ISSUE THREAD

**Issue by strangerdeveloper2810** [strangerdeveloper2810/Final-Booking-Ticket-Movie#12]
Pull new source code and using yarn command for install package

In page home, when i click movie then redirect into page detail of movie. Make layout for page detail.

Checkout branch from maintain branch

**Comment by quan201002** [comment]
code pushed,
Unable to render Tab's children !

**Comment by strangerdeveloper2810** [comment]
task done => develop by me
